name: GitHub Workflow Immortality

on:
  schedule:
    # run once a month on the first day of the month at 00:20 UTC
    - cron: '20 0 1 * *'
  workflow_dispatch: {}

jobs:
  keepalive:
    name: GitHub Workflow Immortality
    runs-on: ubuntu-latest
    permissions:
      actions: write    # 显式开启 Actions 写权限
      contents: write   # 显式开启内容写权限
    steps:
      - name: Keep cronjob based triggers of GitHub workflows alive
        uses: PhrozenByte/gh-workflow-immortality@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repos: ${{ github.repository }}
