name: GitHub Workflow Immortality

on:
  schedule:
    - cron: '20 0 1 * *'
  workflow_dispatch: {}

jobs:
  keepalive:
    name: GitHub Workflow Immortality
    runs-on: ubuntu-latest
    # 1. 移除 permissions: {}，或者改为 write
    permissions:
      actions: write
      contents: write
    steps:
      - name: Keep cronjob based triggers of GitHub workflows alive
        uses: PhrozenByte/gh-workflow-immortality@v1
        with:
          # 2. 将 secret 改为 token (该 Action 的标准参数名)
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          repos: ${{ github.repository }}
